=== michaelxiao7/gordon-360-api/Tests/ApiEndpoints/advanced-search.dtd
<!ELEMENT advanced-search (user*)>
<!ELEMENT user (username, firstname, lastname, major, minor, hall, class, hometown, state, country, department, building)>
<!ATTLIST user
	type CDATA #REQUIRED
>
<!ELEMENT username (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lasttname (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT hall (#PCDATA)>
<!ELEMENT classtype (#PCDATA)>
<!ELEMENT hometown (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT building (#PCDATA)>
>

=== michaelxiao7/gordon-360-api/Tests/ApiEndpoints/advanced-search.xml
<?xml version="1.0"?>
<!DOCTYPE advanced-search SYSTEM "advanced-search.dtd">
<advanced-search>
  <user type="facstaff">
    <username>jonathan.senning</username>
    <firstname>Jon</firstname>
    <lastname>Senning</lastname>
    <hometown>south hamilton</hometown>
    <state>MA</state>
    <xxdepartment>Mathematics and Computer Science</xxdepartment>
    <building>Ken Olsen Science Center</building>
  </user>

  <user type="facstaff">
    <firstname>Chris</firstname>
    <lastname>Jones</lastname>
  </user>
  <!--
  <user type="facstaff">
    <building>Ken Olson Science Center</building>
  </user>
-->
  <user type="student">
    <username>cameron.abbot</username>
    <firstname>Cameron</firstname>
    <lastname>Abbot</lastname>
    <major>Computer Science</major>
    <classtype>Junior</classtype>
    <hometown>Windsor</hometown>
    <state>CT</state>
  </user>

  <user type="student">
    <major>Mathematics</major>
    <!-- <classtype>First Year</classtype> -->
  </user>

  <user type="alum">
    <firstname>Jessica</firstname>
    <lastname>Barrett</lastname>
  </user>

</advanced-search>
